# Generated by Django 3.0.4 on 2020-04-14 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payment', django_enumfield.db.fields.EnumField(default=1, enum=payment.models.PaymentType)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('total_amount', models.IntegerField()),
                ('pay_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('trantype', django_enumfield.db.fields.EnumField(default=1, enum=payment.models.Trantype)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
                ('pledging_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Pledging')),
            ],
        ),
        migrations.CreateModel(
            name='Re_contract',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Transaction')),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
            bases=('payment.transaction',),
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Payment')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=payment.models.Status)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('payment.payment',),
        ),
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Payment')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('payment.payment',),
        ),
    ]
