# Generated by Django 3.0.4 on 2020-04-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='payments/'),
        ),
    ]
