# Generated by Django 3.0.5 on 2020-04-28 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0021_auto_20200425_1614'),
        ('payment', '0002_online_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recontract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('pledging_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Pledging')),
            ],
        ),
        migrations.AlterField(
            model_name='online',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_payment',
            field=django_enumfield.db.fields.EnumField(default=0, enum=payment.models.PaymentType),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pledging_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Pledging'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trantype',
            field=django_enumfield.db.fields.EnumField(default=0, enum=payment.models.Trantype),
        ),
        migrations.DeleteModel(
            name='Re_contract',
        ),
        migrations.AddField(
            model_name='recontract',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Transaction'),
        ),
    ]
