# Generated by Django 3.0.4 on 2020-03-19 00:19

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('dob', models.DateField()),
                ('citizen_id', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.IntegerField()),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('payment_for', django_enumfield.db.fields.EnumField(default=0, enum=management.models.status_pay)),
            ],
        ),
        migrations.CreateModel(
            name='PLEDGING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_balance', models.IntegerField()),
                ('pledge_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(auto_now_add=True)),
                ('contract_term', models.IntegerField()),
                ('type_pled', django_enumfield.db.fields.EnumField(default=0, enum=management.models.status)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.CUSTOMER')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT_PLEDGING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.PAYMENT')),
                ('pled_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.PLEDGING')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_pled',
            field=models.ManyToManyField(through='management.PAYMENT_PLEDGING', to='management.PLEDGING'),
        ),
        migrations.CreateModel(
            name='GOLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('pledging_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.CUSTOMER')),
            ],
        ),
    ]
