# Generated by Django 3.0.5 on 2020-04-28 22:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import management.models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('citizen_id', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('user_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pledging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_balance', models.IntegerField()),
                ('contract_term', models.IntegerField()),
                ('pledge_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField(null=True)),
                ('type_pledging', django_enumfield.db.fields.EnumField(default=1, enum=management.models.PledgingType)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redeemed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('citizen_id', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('redeem_date', models.DateField(auto_now_add=True)),
                ('pledging_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Pledging')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('detail', django_enumfield.db.fields.EnumField(default=0, enum=payment.models.Trantype)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('goldtype', django_enumfield.db.fields.EnumField(default=0, enum=management.models.GoldType)),
                ('pledging_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Pledging')),
            ],
        ),
    ]
