# Generated by Django 3.0.4 on 2020-03-19 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='REDEEMED',
            fields=[
                ('pledging_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.PLEDGING')),
                ('redeem_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('management.pledging',),
        ),
    ]
