# Generated by Django 3.0.4 on 2020-04-15 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_auto_20200414_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gold',
            name='pledging_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Pledging'),
        ),
        migrations.AlterField(
            model_name='pledging',
            name='cus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Customer'),
        ),
    ]
