# Generated by Django 3.0.4 on 2020-04-15 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200415_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='citizen_id',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
