# Generated by Django 3.0.4 on 2020-04-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200415_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemed',
            name='citizen_id',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
