# Generated by Django 3.0.4 on 2020-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_gold_goldtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledging',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
