# Generated by Django 3.0.5 on 2020-04-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20200425_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledging',
            old_name='pledge_balanca',
            new_name='pledge_balance',
        ),
    ]
