# Generated by Django 3.0.4 on 2020-04-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20200425_0216'),
        ('management', '0017_auto_20200425_0233'),
    ]

    operations = [
    ]
