# Generated by Django 3.0.4 on 2020-04-25 14:12

from django.db import migrations
import django_enumfield.db.fields
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_merge_20200425_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='detail',
            field=django_enumfield.db.fields.EnumField(default=0, enum=payment.models.Trantype),
        ),
    ]
