# Generated by Django 3.0.4 on 2020-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_log_cus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
